### ISSUE TITLE
asm6 syntax support

### ISSUE THREAD

**Issue by Xkeeper0** [MatthewCallis/language-65asm#12]
It would be nice to have [asm6](https://github.com/freem/asm6f) 6502 support, specifically highlighting of `.db`/`.dw`/`.byte`/`.word` keywords, `.pad`/`.include`/etc. directives, `ifdef/endif/ifndef` conditionals, and so on. It seems like a lot of 6502 syntax providers rarely actually do much in the way of syntax highlighting 😕

**Comment by georgjz** [comment]
Thanks for your request. I have started to re-write the grammars of this package for the new tree-sitter grammar/parser system that Atom will use in the near future. The problem now is, that there is still a bug that prevents from tree-sitter grammars to be selected in Atom (see [here](https://github.com/atom/atom/issues/17029) for details). 

I'll gladly add support for asm6. I had a quick glance at the assembler, I think you could use the cc65 grammar for 6502 as a temporary workaround. It supports most of the assembler directives you mentioned, except for those NES-specific directives, and those pseudo-opcodes.

**Comment by georgjz** [comment]
I found myself with an hour off today, I added a simple grammar for ASM6f, it's not perfect, but should do the trick until tree-sitter grammars work properly.
