### ISSUE TITLE
Bug in acme grammar

### ISSUE THREAD

**Issue by godot64** [MatthewCallis/language-65asm#14]
Hi Matt,
please change line 127 in acme grammar:
        match:  '\\!|\\+|\\-|\\/|\\*|<<|>>|&|\\||\\^|=|<|>|\\:|\\|\\|'
to this:
        match:  '\\!|\\+|\\-|\\/|\\*|<<|>>|&|\\||\\^|=|<|>|\\:'

(the rightmost entries must be cleared). After that the arithmetic operators will finally work and be highlighted. 

I know it's a late call, sorry. But see my handle (GoDot), it explains… ;-) Files to test you can find on my GitHub repository for GoDot C64 Image Processing (https://github.com/godot64/). 

Arndt

**Comment by MatthewCallis** [comment]
Sorry for taking so long, pushing a new version now!

**Comment by godot64** [comment]
-----Ursprüngliche Nachricht----- 
Sent: Friday, August 30, 2019 12:52 AM

> Sorry for taking so long, pushing a new version now!

Thumbs up! ;-)

Arndt

---
GoDot - C64 Image Processing
https://www.godot64.de
