### ISSUE TITLE
Uncaught Error: target of repeat operator is not specified

### ISSUE THREAD

**Issue by SebastienBellanger** [MatthewCallis/language-65asm#8]
I'm trying to use the package for ACME assembler files and I get this error message.
I've tracked it down to the line 
`# Macro control
{
match:  '\\b(?i:\!macro|\+[a-zA-Z0-9)\\b'
name:   'support.function.pseudo.acme'
}`
in acme.cson

That's how far I got as my regex isn't up to for the task :)

I'm using Atom 1.27.2 on a mac

**Comment by georgjz** [comment]
I fixed that. I will place a Pull Request as soon as I finish some other things I wish to improve. Should happen today.
